### ISSUE TITLE
panic: Unable to create main window: TTM_ADDTOOL failed

### ISSUE THREAD

**Issue by usernameisnull** [dawei101/tongsheClient.shadowsocks-go#2]
windows上一运行就报错呢,
把tongshe.go的最后一行改为了
systray.Run(onTrayReady,nil)
把proxy.go的300行和301行改为了
go ss.PipeThenClose(conn, remote,nil)
ss.PipeThenClose(remote, conn,nil)

都只是因为依赖的库函数发生了改变,添加了个nil
```
panic: Unable to create main window: TTM_ADDTOOL failed

Stack:
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x432, 0x0, 0xc00008d7d8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
github.com/lxn/walk.newErr(...)
        /root/gopath/src/github.com/lxn/walk/error.go:81
github.com/lxn/walk.newError(0x94b210, 0x12, 0x0, 0xc00008d7d8)
        /root/gopath/src/github.com/lxn/walk/error.go:85 +0x2e
github.com/lxn/walk.(*ToolTip).addTool(0xc00008f900, 0xa1c260, 0xc000122000, 0xa1c200, 0xc000122000, 0xc00008d888)
        /root/gopath/src/github.com/lxn/walk/tooltip.go:185 +0x105
github.com/lxn/walk.(*ToolTip).AddTool(...)
        /root/gopath/src/github.com/lxn/walk/tooltip.go:160
github.com/lxn/walk.(*WidgetBase).init(0xc000122000, 0xa1c260, 0xc000122000, 0xa1c260, 0xc000122000)
        /root/gopath/src/github.com/lxn/walk/widget.go:137 +0xed
github.com/lxn/walk.InitWindow(0x1444390, 0xc000122000, 0xa18c20, 0xc000016c00, 0x95186a, 0x1c, 0x1000050000000, 0x0, 0x0)
        /root/gopath/src/github.com/lxn/walk/window.go:637 +0x41d
github.com/lxn/walk.InitWidget(0xa1c260, 0xc000122000, 0xa18c20, 0xc000016c00, 0x95186a, 0x1c, 0x1000050000000, 0x93ffc0, 0x1444000)
        /root/gopath/src/github.com/lxn/walk/widget.go:110 +0xc3
github.com/lxn/walk.NewCompositeWithStyle(0xa18c20, 0xc000016c00, 0xc000000000, 0xa18c20, 0xc000016c00, 0xa1b620)
        /root/gopath/src/github.com/lxn/walk/composite.go:30 +0xdb
github.com/lxn/walk.NewComposite(0xa1b620, 0xc000016c00, 0xc000016c00, 0xa1b620, 0xc000016c00)
        /root/gopath/src/github.com/lxn/walk/composite.go:45 +0x68
github.com/lxn/walk.(*FormBase).init(0xc000016c00, 0xa1e680, 0xc000016c00, 0xa1e680, 0xc000016c00)
        /root/gopath/src/github.com/lxn/walk/form.go:105 +0x67
github.com/lxn/walk.InitWindow(0xa18c20, 0xc000016c00, 0x0, 0x0, 0x9521cd, 0x1d, 0x1000000cf0000, 0x0, 0x0)
        /root/gopath/src/github.com/lxn/walk/window.go:629 +0xb64
github.com/lxn/walk.NewMainWindowWithName(0x0, 0x0, 0x0, 0x0, 0x0)
        /root/gopath/src/github.com/lxn/walk/mainwindow.go:41 +0xb7
github.com/lxn/walk.NewMainWindow(...)
        /root/gopath/src/github.com/lxn/walk/mainwindow.go:34
github.com/getlantern/systray.nativeLoop(0x0, 0x0, 0x0, 0x0)
        /root/gopath/src/github.com/getlantern/systray/systray_windows.go:28 +0x46
github.com/getlantern/systray.RunWithAppWindow(0x0, 0x0, 0x0, 0x0, 0x98c5f8, 0x0)
        /root/gopath/src/github.com/getlantern/systray/systray.go:85 +0xb0
github.com/getlantern/systray.Run(...)
        /root/gopath/src/github.com/getlantern/systray/systray.go:56
main.main()
        /root/gopath/src/github.com/dawei101/tongsheClient.shadowsocks-go-ui/tongshe.go:283 +0x4b


goroutine 1 [running, locked to thread]:
github.com/getlantern/systray.fail(...)
        /root/gopath/src/github.com/getlantern/systray/systray_windows.go:185
github.com/getlantern/systray.nativeLoop(0x0, 0x0, 0x0, 0x0)
        /root/gopath/src/github.com/getlantern/systray/systray_windows.go:30 +0xb86
github.com/getlantern/systray.RunWithAppWindow(0x0, 0x0, 0x0, 0x0, 0x98c5f8, 0x0)
        /root/gopath/src/github.com/getlantern/systray/systray.go:85 +0xb0
github.com/getlantern/systray.Run(...)
        /root/gopath/src/github.com/getlantern/systray/systray.go:56
main.main()
        /root/gopath/src/github.com/dawei101/tongsheClient.shadowsocks-go-ui/tongshe.go:283 +0x4b
```

**Comment by usernameisnull** [comment]
解决了,编译之前加个文件
[TTM_ADDTOOL failed](https://github.com/lxn/win/issues/61)

> 文件,tongshe.exe.manifest,放在bin目录下
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
	<assemblyIdentity version="1.0.0.0" processorArchitecture="*" name="SomeFunkyNameHere" type="win32"/>
	<dependency>
		<dependentAssembly>
			<assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/>
		</dependentAssembly>
	</dependency>
	<application xmlns="urn:schemas-microsoft-com:asm.v3">
		<windowsSettings>
			<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, PerMonitor</dpiAwareness>
			<dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">True</dpiAware>
		</windowsSettings>
	</application>
</assembly>
```
